name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "WEB_API_KEY=${{ secrets.WEB_API_KEY }}" >> .env
          echo "WEB_APP_ID=${{ secrets.WEB_APP_ID }}" >> .env
          echo "WEB_MESSAGING_SENDER_ID=${{ secrets.WEB_MESSAGING_SENDER_ID }}" >> .env
          echo "WEB_PROJECT_ID=${{ secrets.WEB_PROJECT_ID }}" >> .env
          echo "WEB_AUTH_DOMAIN=${{ secrets.WEB_AUTH_DOMAIN }}" >> .env
          echo "WEB_STORAGE_BUCKET=${{ secrets.WEB_STORAGE_BUCKET }}" >> .env
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env

      - name: Create dummy service account
        run: |
          mkdir -p assets
          echo "{}" > assets/service-account.json

      - name: Build Web
        run: flutter build web --release --base-href "/Asiimov/"
        
      - name: Add .nojekyll
        run: touch build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
